type: object
description: Configuration specific to the payment provider, utilized for billing the customer. This object contains settings and parameters necessary for processing payments and invoicing the customer.
properties:
  invoice_grace_period:
    type: integer
    example: 3
    description: The grace period, expressed in days, for the invoice. This period refers to the additional time granted to the customer beyond the invoice due date to adjust usage and line items
  subscription_invoice_issuing_date_anchor:
    type: string
    example: next_period_start
    description: |-
      Defines whether the issuing date follows the current billing period's end date or the next period starting date.
      Accepted values: `current_period_end`, `next_period_start` or null.
    enum:
      - current_period_end
      - next_period_start
  subscription_invoice_issuing_date_adjustment:
    type: string
    example: keep_anchor
    description: |-
      The logic applied on top of the subscription_invoice_issuing_date_anchor rule. You can opt to use the invoice finalization date, that includes any configured grace period.
      Accepted values: `align_with_finalization_date`, `keep_anchor` or null.
    enum:
      - align_with_finalization_date
      - keep_anchor
  payment_provider:
    type: string
    example: stripe
    description: |-
      The payment provider utilized to initiate payments for invoices issued by Lago.
      Accepted values: `stripe`, `adyen`, `gocardless` or null. This field is required if you intend to assign a `provider_customer_id`.
    enum:
      - stripe
      - adyen
      - gocardless
  payment_provider_code:
    type: string
    example: stripe-eu-1
    description: Unique code used to identify a payment provider connection.
  provider_customer_id:
    type: string
    example: "cus_12345"
    description: The customer ID within the payment provider's system. If this field is not provided, Lago has the option to create a new customer record within the payment provider's system on behalf of the customer
  sync:
    type: boolean
    example: true
    description: Set this field to `true` if you want to create the customer in the payment provider synchronously with the customer creation process in Lago. This option is applicable only when the `provider_customer_id` is `null` and the customer is automatically created in the payment provider through Lago. By default, the value is set to `false`
  sync_with_provider:
    type: boolean
    example: true
    description: Set this field to `true` if you want to create a customer record in the payment provider's system. This option is applicable only when the `provider_customer_id` is null and the `sync_with_provider` field is set to `true`. By default, the value is set to `false`
  document_locale:
    type: string
    example: fr
    description: The document locale, specified in the ISO 639-1 format. This field represents the language or locale used for the documents issued by Lago
  provider_payment_methods:
    type:
      - array
      - "null"
    items:
      type: string
    description: Specifies the available payment methods that can be used for this customer when `payment_provider` is set to `stripe`. The `provider_payment_methods` field is an array that allows multiple payment options to be defined. If this field is not explicitly set, the payment methods will be set to `card`. For now, possible values are `card`, `sepa_debit`, `us_bank_account`, `bacs_debit`, `boleto`, `link`, `crypto` and `customer_balance`. Note that when `link` is selected, `card` should also be provided in the array. When `customer_balance` is selected, no other payment can be selected.
    example:
      - card
      - sepa_debit
      - us_bank_account
      - bacs_debit
      - link
      - boleto
      - crypto
      - customer_balance
